import { useState, useEffect } from 'react';
import { supabase } from '../supabase';

const useSupabase = (tableName, orderBy = 'created_at') => {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchData = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from(tableName)
        .select('*')
        .order(orderBy, { ascending: false });
      
      if (error) throw error;
      setData(data);
    } catch (err) {
      setError(err);
      console.error(`Error fetching ${tableName}:`, err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [tableName]);

  const create = async (item) => {
    // Remove id if it's auto-generated by Supabase (optional, but safer)
    // But our schema uses uuid default gen_random_uuid(), so we can omit it or pass it.
    // If we pass it, we ensure frontend generated IDs are used (good for migration).
    const { data: newItem, error } = await supabase
      .from(tableName)
      .insert(item)
      .select()
      .single();
    
    if (error) throw error;
    setData([newItem, ...data]);
    return newItem;
  };

  const update = async (id, updates) => {
    const { data: updatedItem, error } = await supabase
      .from(tableName)
      .update(updates)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    setData(data.map(item => item.id === id ? updatedItem : item));
    return updatedItem;
  };

  const remove = async (id) => {
    const { error } = await supabase
      .from(tableName)
      .delete()
      .eq('id', id);

    if (error) throw error;
    setData(data.filter(item => item.id !== id));
  };

  return { data, loading, error, create, update, remove, refresh: fetchData };
};

export default useSupabase;
